/*
# Veloura Manager V2 — Core Schema

1. Purpose
   Builds the complete relational data model for Veloura Manager V2, a perfume
   business financial management system. The Inventory Batch is the central
   entity: products, sales, batch expenses, and wallet allocations all attach
   to a batch. Customers and suppliers are business-level entities.

2. Tables created (11 core + 1 helper)
   - settings            : single-row business configuration
   - suppliers           : vendors that supply inventory batches
   - inventory_batches   : the core entity — one stock purchase cycle
   - products            : perfumes, each belonging to exactly one batch
   - customers           : buyers (business-level, not batch-scoped)
   - sales               : one record per sale transaction
   - expenses            : unified batch + business expenses
   - wallet_transactions : append-only ledger for Needs/Savings/Growth wallets
   - notifications       : system + business alerts
   - activity_logs       : audit trail for every important action
   - id_sequences        : counter table powering human-readable IDs (BAT-000001 etc.)

3. ID strategy
   Human-readable business IDs (BAT-000001, PRD-000001, SAL-000001, ...) are
   generated by a `generate_business_id(prefix)` PL/pgSQL function backed by
   the `id_sequences` table. These are stored in `<entity>_code` columns and
   are immutable after creation. UUIDs remain the primary keys for joins.

4. Computed vs stored values
   Per spec section 5.18, derived values (wallet balances, customer lifetime
   value, dashboard KPIs, batch completion %) are NOT stored. They are
   computed in the calculation services from source rows. Batch aggregates
   (gross_revenue, gross_profit, net_profit, roi, completion_percentage,
   remaining_stock) ARE stored because they are historically meaningful and
   expensive to recompute across all sales.

5. Triggers
   - `set_updated_at`    : maintains updated_at on every update.
   - `enforce_single_settings_row` : guarantees the settings table never has
     more than one row.

6. Security (RLS)
   This is a single-tenant, no-auth app (Version 2 = single business owner,
   no sign-in screen per spec 3.2). All policies use `TO anon, authenticated`
   with `USING (true)` / `WITH CHECK (true)` because the data is intentionally
   shared within the single business. This matches the bolt-database guidance
   for no-auth single-tenant apps.

7. Data integrity
   - Foreign keys enforce: product->batch, sale->product+customer, batch->supplier,
     batch expense->batch, wallet_transaction->batch (nullable for direct
     transfers/withdrawals).
   - `CHECK` constraints enforce valid enum values for status / type columns.
   - Settings table locked to a single row.
*/

-- ============================================================
-- ID SEQUENCE TABLE + GENERATOR
-- ============================================================
CREATE TABLE IF NOT EXISTS id_sequences (
  prefix text PRIMARY KEY,
  next_value integer NOT NULL DEFAULT 1
);

ALTER TABLE id_sequences ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_id_sequences" ON id_sequences;
CREATE POLICY "anon_rw_id_sequences" ON id_sequences FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_id_sequences_ins" ON id_sequences;
CREATE POLICY "anon_rw_id_sequences_ins" ON id_sequences FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_id_sequences_upd" ON id_sequences;
CREATE POLICY "anon_rw_id_sequences_upd" ON id_sequences FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_id_sequences_del" ON id_sequences;
CREATE POLICY "anon_rw_id_sequences_del" ON id_sequences FOR DELETE
  TO anon, authenticated USING (true);

CREATE OR REPLACE FUNCTION generate_business_id(p_prefix text)
RETURNS text
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_next integer;
BEGIN
  INSERT INTO id_sequences (prefix, next_value)
  VALUES (p_prefix, 1)
  ON CONFLICT (prefix)
  DO UPDATE SET next_value = id_sequences.next_value + 1
  RETURNING next_value INTO v_next;
  RETURN p_prefix || '-' || lpad(v_next::text, 6, '0');
END;
$$;

-- ============================================================
-- SETTINGS (single row)
-- ============================================================
CREATE TABLE IF NOT EXISTS settings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  business_name text NOT NULL,
  owner_name text NOT NULL,
  phone text,
  email text,
  business_address text,
  currency text NOT NULL DEFAULT 'GHS',
  currency_symbol text NOT NULL DEFAULT '₵',
  theme text NOT NULL DEFAULT 'light' CHECK (theme IN ('light','dark')),
  low_stock_threshold integer NOT NULL DEFAULT 5,
  batch_completion_threshold numeric NOT NULL DEFAULT 10 CHECK (batch_completion_threshold BETWEEN 0 AND 100),
  needs_percentage numeric NOT NULL DEFAULT 40 CHECK (needs_percentage BETWEEN 0 AND 100),
  savings_percentage numeric NOT NULL DEFAULT 35 CHECK (savings_percentage BETWEEN 0 AND 100),
  growth_percentage numeric NOT NULL DEFAULT 25 CHECK (growth_percentage BETWEEN 0 AND 100),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_settings" ON settings;
CREATE POLICY "anon_rw_settings" ON settings FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_settings_ins" ON settings;
CREATE POLICY "anon_rw_settings_ins" ON settings FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_settings_upd" ON settings;
CREATE POLICY "anon_rw_settings_upd" ON settings FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_settings_del" ON settings;
CREATE POLICY "anon_rw_settings_del" ON settings FOR DELETE
  TO anon, authenticated USING (true);

CREATE OR REPLACE FUNCTION enforce_single_settings_row()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  IF (SELECT count(*) FROM settings) >= 1 AND TG_OP = 'INSERT' THEN
    RAISE EXCEPTION 'Settings table can only contain one row';
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS settings_single_row ON settings;
CREATE TRIGGER settings_single_row
  BEFORE INSERT ON settings
  FOR EACH ROW EXECUTE FUNCTION enforce_single_settings_row();

-- ============================================================
-- SUPPLIERS
-- ============================================================
CREATE TABLE IF NOT EXISTS suppliers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  supplier_code text UNIQUE NOT NULL,
  supplier_name text NOT NULL,
  phone text,
  email text,
  location text,
  contact_person text,
  notes text,
  status text NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Archived','Deleted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_suppliers" ON suppliers;
CREATE POLICY "anon_rw_suppliers" ON suppliers FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_suppliers_ins" ON suppliers;
CREATE POLICY "anon_rw_suppliers_ins" ON suppliers FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_suppliers_upd" ON suppliers;
CREATE POLICY "anon_rw_suppliers_upd" ON suppliers FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_suppliers_del" ON suppliers;
CREATE POLICY "anon_rw_suppliers_del" ON suppliers FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- INVENTORY BATCHES (core entity)
-- ============================================================
CREATE TABLE IF NOT EXISTS inventory_batches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  batch_code text UNIQUE NOT NULL,
  batch_name text NOT NULL,
  supplier_id uuid NOT NULL REFERENCES suppliers(id) ON DELETE RESTRICT,
  purchase_date date NOT NULL DEFAULT CURRENT_DATE,
  expected_arrival date,
  arrival_date date,
  purchase_cost numeric NOT NULL DEFAULT 0 CHECK (purchase_cost >= 0),
  transport_cost numeric NOT NULL DEFAULT 0 CHECK (transport_cost >= 0),
  loading_cost numeric NOT NULL DEFAULT 0 CHECK (loading_cost >= 0),
  import_duty numeric NOT NULL DEFAULT 0 CHECK (import_duty >= 0),
  insurance numeric NOT NULL DEFAULT 0 CHECK (insurance >= 0),
  other_costs numeric NOT NULL DEFAULT 0 CHECK (other_costs >= 0),
  total_batch_cost numeric NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'Draft' CHECK (status IN ('Draft','Purchased','Selling','Almost Finished','Completed','Archived')),
  completion_percentage numeric NOT NULL DEFAULT 0 CHECK (completion_percentage BETWEEN 0 AND 100),
  remaining_stock integer NOT NULL DEFAULT 0 CHECK (remaining_stock >= 0),
  gross_revenue numeric NOT NULL DEFAULT 0,
  gross_profit numeric NOT NULL DEFAULT 0,
  net_profit numeric NOT NULL DEFAULT 0,
  roi numeric NOT NULL DEFAULT 0,
  notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE inventory_batches ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_batches" ON inventory_batches;
CREATE POLICY "anon_rw_batches" ON inventory_batches FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_batches_ins" ON inventory_batches;
CREATE POLICY "anon_rw_batches_ins" ON inventory_batches FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_batches_upd" ON inventory_batches;
CREATE POLICY "anon_rw_batches_upd" ON inventory_batches FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_batches_del" ON inventory_batches;
CREATE POLICY "anon_rw_batches_del" ON inventory_batches FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_batches_supplier ON inventory_batches(supplier_id);
CREATE INDEX IF NOT EXISTS idx_batches_status ON inventory_batches(status);

-- ============================================================
-- PRODUCTS
-- ============================================================
CREATE TABLE IF NOT EXISTS products (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  product_code text UNIQUE NOT NULL,
  batch_id uuid NOT NULL REFERENCES inventory_batches(id) ON DELETE RESTRICT,
  product_name text NOT NULL,
  brand text,
  category text,
  sku text,
  barcode text,
  cost_price numeric NOT NULL DEFAULT 0 CHECK (cost_price >= 0),
  selling_price numeric NOT NULL DEFAULT 0 CHECK (selling_price >= 0),
  initial_stock integer NOT NULL DEFAULT 0 CHECK (initial_stock >= 0),
  current_stock integer NOT NULL DEFAULT 0 CHECK (current_stock >= 0),
  reorder_level integer NOT NULL DEFAULT 0 CHECK (reorder_level >= 0),
  description text,
  image_url text,
  status text NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Archived','Deleted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_products" ON products;
CREATE POLICY "anon_rw_products" ON products FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_products_ins" ON products;
CREATE POLICY "anon_rw_products_ins" ON products FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_products_upd" ON products;
CREATE POLICY "anon_rw_products_upd" ON products FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_products_del" ON products;
CREATE POLICY "anon_rw_products_del" ON products FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_products_batch ON products(batch_id);
CREATE INDEX IF NOT EXISTS idx_products_status ON products(status);

-- ============================================================
-- CUSTOMERS
-- ============================================================
CREATE TABLE IF NOT EXISTS customers (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  customer_code text UNIQUE NOT NULL,
  customer_name text NOT NULL,
  phone text,
  email text,
  location text,
  gender text CHECK (gender IN ('Male','Female','Other') OR gender IS NULL),
  birthday date,
  notes text,
  status text NOT NULL DEFAULT 'Active' CHECK (status IN ('Active','Archived','Deleted')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE customers ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_customers" ON customers;
CREATE POLICY "anon_rw_customers" ON customers FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_customers_ins" ON customers;
CREATE POLICY "anon_rw_customers_ins" ON customers FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_customers_upd" ON customers;
CREATE POLICY "anon_rw_customers_upd" ON customers FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_customers_del" ON customers;
CREATE POLICY "anon_rw_customers_del" ON customers FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- SALES
-- ============================================================
CREATE TABLE IF NOT EXISTS sales (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  sale_code text UNIQUE NOT NULL,
  batch_id uuid NOT NULL REFERENCES inventory_batches(id) ON DELETE RESTRICT,
  product_id uuid NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
  customer_id uuid REFERENCES customers(id) ON DELETE SET NULL,
  sale_date timestamptz NOT NULL DEFAULT now(),
  quantity integer NOT NULL DEFAULT 1 CHECK (quantity > 0),
  unit_cost numeric NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  unit_price numeric NOT NULL DEFAULT 0 CHECK (unit_price >= 0),
  discount numeric NOT NULL DEFAULT 0 CHECK (discount >= 0),
  discount_type text NOT NULL DEFAULT 'Amount' CHECK (discount_type IN ('Amount','Percent')),
  total_cost numeric NOT NULL DEFAULT 0,
  total_sale numeric NOT NULL DEFAULT 0,
  profit numeric NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT 'Cash' CHECK (payment_method IN ('Cash','Mobile Money','Bank Transfer','Card','Credit')),
  reference_number text,
  status text NOT NULL DEFAULT 'Completed' CHECK (status IN ('Completed','Voided','Refunded')),
  notes text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE sales ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_sales" ON sales;
CREATE POLICY "anon_rw_sales" ON sales FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_sales_ins" ON sales;
CREATE POLICY "anon_rw_sales_ins" ON sales FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_sales_upd" ON sales;
CREATE POLICY "anon_rw_sales_upd" ON sales FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_sales_del" ON sales;
CREATE POLICY "anon_rw_sales_del" ON sales FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_sales_batch ON sales(batch_id);
CREATE INDEX IF NOT EXISTS idx_sales_product ON sales(product_id);
CREATE INDEX IF NOT EXISTS idx_sales_customer ON sales(customer_id);
CREATE INDEX IF NOT EXISTS idx_sales_date ON sales(sale_date);
CREATE INDEX IF NOT EXISTS idx_sales_status ON sales(status);

-- ============================================================
-- EXPENSES (unified batch + business)
-- ============================================================
CREATE TABLE IF NOT EXISTS expenses (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  expense_code text UNIQUE NOT NULL,
  expense_type text NOT NULL CHECK (expense_type IN ('Batch','Business')),
  batch_id uuid REFERENCES inventory_batches(id) ON DELETE SET NULL,
  category text NOT NULL,
  expense_name text NOT NULL,
  amount numeric NOT NULL DEFAULT 0 CHECK (amount > 0),
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  description text,
  receipt_url text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE expenses ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_expenses" ON expenses;
CREATE POLICY "anon_rw_expenses" ON expenses FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_expenses_ins" ON expenses;
CREATE POLICY "anon_rw_expenses_ins" ON expenses FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_expenses_upd" ON expenses;
CREATE POLICY "anon_rw_expenses_upd" ON expenses FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_expenses_del" ON expenses;
CREATE POLICY "anon_rw_expenses_del" ON expenses FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_expenses_batch ON expenses(batch_id);
CREATE INDEX IF NOT EXISTS idx_expenses_type ON expenses(expense_type);
CREATE INDEX IF NOT EXISTS idx_expenses_date ON expenses(expense_date);

-- ============================================================
-- WALLET TRANSACTIONS (append-only ledger)
-- ============================================================
CREATE TABLE IF NOT EXISTS wallet_transactions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  transaction_code text UNIQUE NOT NULL,
  wallet text NOT NULL CHECK (wallet IN ('Needs','Savings','Growth')),
  transaction_type text NOT NULL CHECK (transaction_type IN ('Allocation','Expense','Transfer','Withdrawal','Adjustment')),
  batch_id uuid REFERENCES inventory_batches(id) ON DELETE SET NULL,
  reference_id uuid,
  amount numeric NOT NULL DEFAULT 0,
  balance_after numeric,
  reason text,
  created_by text NOT NULL DEFAULT 'Owner',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE wallet_transactions ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_wallet_tx" ON wallet_transactions;
CREATE POLICY "anon_rw_wallet_tx" ON wallet_transactions FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_wallet_tx_ins" ON wallet_transactions;
CREATE POLICY "anon_rw_wallet_tx_ins" ON wallet_transactions FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_wallet_tx_upd" ON wallet_transactions;
CREATE POLICY "anon_rw_wallet_tx_upd" ON wallet_transactions FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_wallet_tx_del" ON wallet_transactions;
CREATE POLICY "anon_rw_wallet_tx_del" ON wallet_transactions FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_wallet_tx_wallet ON wallet_transactions(wallet);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_batch ON wallet_transactions(batch_id);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_date ON wallet_transactions(created_at);
CREATE INDEX IF NOT EXISTS idx_wallet_tx_type ON wallet_transactions(transaction_type);

-- ============================================================
-- NOTIFICATIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS notifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  notification_code text UNIQUE NOT NULL,
  type text NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  reference_type text,
  reference_id uuid,
  priority text NOT NULL DEFAULT 'Medium' CHECK (priority IN ('High','Medium','Low')),
  read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_notifications" ON notifications;
CREATE POLICY "anon_rw_notifications" ON notifications FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_notifications_ins" ON notifications;
CREATE POLICY "anon_rw_notifications_ins" ON notifications FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_notifications_upd" ON notifications;
CREATE POLICY "anon_rw_notifications_upd" ON notifications FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_notifications_del" ON notifications;
CREATE POLICY "anon_rw_notifications_del" ON notifications FOR DELETE
  TO anon, authenticated USING (true);

-- ============================================================
-- ACTIVITY LOGS
-- ============================================================
CREATE TABLE IF NOT EXISTS activity_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  log_code text UNIQUE NOT NULL,
  actor text NOT NULL DEFAULT 'Owner',
  action text NOT NULL,
  module text NOT NULL,
  reference_id uuid,
  description text,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE activity_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "anon_rw_activity_logs" ON activity_logs;
CREATE POLICY "anon_rw_activity_logs" ON activity_logs FOR SELECT
  TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "anon_rw_activity_logs_ins" ON activity_logs;
CREATE POLICY "anon_rw_activity_logs_ins" ON activity_logs FOR INSERT
  TO anon, authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_activity_logs_upd" ON activity_logs;
CREATE POLICY "anon_rw_activity_logs_upd" ON activity_logs FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "anon_rw_activity_logs_del" ON activity_logs;
CREATE POLICY "anon_rw_activity_logs_del" ON activity_logs FOR DELETE
  TO anon, authenticated USING (true);

CREATE INDEX IF NOT EXISTS idx_activity_logs_module ON activity_logs(module);
CREATE INDEX IF NOT EXISTS idx_activity_logs_ref ON activity_logs(reference_id);
CREATE INDEX IF NOT EXISTS idx_activity_logs_date ON activity_logs(created_at);

-- ============================================================
-- UPDATED_AT TRIGGER (applies to all tables with updated_at)
-- ============================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS set_updated_at ON settings;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON suppliers;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON suppliers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON inventory_batches;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON inventory_batches
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON products;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS set_updated_at ON customers;
CREATE TRIGGER set_updated_at BEFORE UPDATE ON customers
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();
